[package]
name = "leptos-tutorial"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["ui"]

[dependencies]
ui = { path = "./ui" }
leptos = { version = "0.8.19", features = ["csr"] }
leptos_meta = "0.8.6"
leptos_router = "0.8.13"
lucide-leptos = { version = "3.11.0", features = ["all-icons"] }
