[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
floating-ui-leptos = "0.6.0"
leptos = { version = "0.8.19", features = ["csr"] }
web-sys = { version = "0.3.98", features = ["Storage", "MediaQueryList"] }
leptos-node-ref = "0.2.0"
send_wrapper = "0.6.0"
tw_merge = { version = "0.1.21", features = ["variant"] }
