//! `cargo nocli components add` and `list`.

use crate::{config::Config, manifest, remote::Source, rewrite};
use anyhow::{Context, Result};
use std::{
    collections::{BTreeSet, VecDeque},
    fs,
    path::Path,
};

pub async fn add(source: &Source, names: &[String], force: bool) -> Result<()> {
    manifest::require_cargo_project()?;
    let config = Config::load()?;
    let module_path = config.module_path()?;
    let dir = Path::new(&config.paths.components);
    fs::create_dir_all(dir).with_context(|| format!("creating {}", config.paths.components))?;

    let mut queue: VecDeque<String> = names.iter().cloned().collect();
    let mut seen: BTreeSet<String> = names.iter().cloned().collect();
    let mut installed: Vec<String> = Vec::new();
    let mut written = 0usize;
    let mut kept = 0usize;
    let mut uses_icons = false;

    // Components built on other components pull those in too, read out of the source just
    // downloaded rather than from a list that could drift.
    while let Some(name) = queue.pop_front() {
        let file = source.component(&name).await?;
        let out = rewrite::rewrite(&file, &module_path);
        uses_icons |= out.uses_icons;

        let path = dir.join(format!("{name}.rs"));
        // Never write over a file already there: the installed source is the project's to edit.
        if path.exists() && !force {
            println!("  kept      {} (already here)", path.display());
            kept += 1;
        } else {
            fs::write(&path, &out.source).with_context(|| format!("writing {}", path.display()))?;
            let reason = if names.contains(&name) {
                "added"
            } else {
                "needed by"
            };
            println!("  {reason:<9} {}", path.display());
            written += 1;
        }
        installed.push(name);

        for dep in out.component_deps {
            if seen.insert(dep.clone()) {
                queue.push_back(dep);
            }
        }
    }

    write_module(dir)?;

    let mut features = manifest::current_features()?;
    features.insert("primitives".into());
    if uses_icons {
        features.insert("icons".into());
    }
    // Only what was installed: the rest are feature edges cargo works out from the library's own
    // Cargo.toml.
    features.extend(installed.iter().cloned());

    manifest::add_dependency(&features, source.checkout())?;

    print!("\n{written} written");
    if kept > 0 {
        print!(", {kept} left alone (--force overwrites)");
    }
    println!(" in {}", config.paths.components);
    Ok(())
}

/// Rewritten from the directory, so a file removed by hand stops being declared.
fn write_module(dir: &Path) -> Result<()> {
    let mut names: Vec<String> = fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            name.strip_suffix(".rs")
                .filter(|n| *n != "mod")
                .map(str::to_string)
        })
        .collect();
    names.sort();

    let mut out = String::from(
        "// Generated by `cargo nocli`. The components are yours to edit; this list is not —\n\
         // it is rewritten from the directory every time something is added.\n\n",
    );
    for name in &names {
        out.push_str(&format!("pub mod {name};\n"));
    }
    out.push_str("\npub mod prelude {\n");
    for name in &names {
        out.push_str(&format!("    pub use super::{name}::*;\n"));
    }
    out.push_str("}\n");

    fs::write(dir.join("mod.rs"), out).context("writing mod.rs")
}

pub async fn list(source: &Source) -> Result<()> {
    let names = source.catalogue().await?;
    let installed: BTreeSet<String> = Config::load()
        .ok()
        .and_then(|c| fs::read_dir(c.paths.components).ok())
        .map(|entries| {
            entries
                .filter_map(|e| e.ok())
                .filter_map(|e| {
                    e.file_name()
                        .to_string_lossy()
                        .strip_suffix(".rs")
                        .map(str::to_string)
                })
                .collect()
        })
        .unwrap_or_default();

    for name in &names {
        let mark = if installed.contains(name) { "*" } else { " " };
        println!("{mark} {name}");
    }
    println!("\n{} available, {} installed", names.len(), installed.len());
    Ok(())
}
